#!/usr/bin/env bash
AUTOCOCODIR=$(realpath "$0")
AUTOCOCODIR=$(dirname "$AUTOCOCODIR")
SCRIPTDIR="$AUTOCOCODIR/scripts"

source "$SCRIPTDIR/autococo.sh"

function call_emulator() {
#debugfc $FUNCNAME "$@"
	if [ ! -x "$SCRIPTDIR/emulator.$EMULATOR.sh" ] ; then
		error emulator "$EMULATOR" does not exist!
		return 1
	fi

	echo . "$SCRIPTDIR/emulator.$EMULATOR.sh" "$@"
}

function cmd_download() { # URL
#debugfc $FUNCNAME "$@"
	file=$(autococo_download "$@")
	if [[ $? == 0 ]] ; then
		echo "Download ok. Local file at $file"
		return 0
	else
		echo "ERROR: Download failed!"
		return 1
	fi
}

function cmd_infer() { # dsk/zip/cas file
#debugfc $FUNCNAME "$@"
	local ext="${1##*.}"
	filename=$(basename "$1")
	local out
	if [[ -n -z "$2" ]] ; then
		out="$2"
	else
		out="${filename%.*}.autococo"
	fi
	
	inferred__=(inferred_package inferred_setup)
	inferred_package_=(inferred_package_status)
	inferred_package_status="inferred"
	inferred_setup_=()
	infer_archive_cocoarchive "$1"

	echo "FILE: $1"
	case ${ext,,} in
	zip)
		infer_zip "$1"
		;;
	dsk)
		infer_dsk "$1"
		;;
	cas)
		infer_cas "$1"
		;;
	rom | ccc)
		infer_ccc "$1"
		;;
	*)
		echo Cannot infer for extension "$ext"
		return 1
	esac

#echo VARIABLES[]: ${!inferred_@}
#debug out="$out"
	save_yaml inferred "$out"

	return $?
}

function cmd_run() { # autococo.file dsk/zip/cas file
#echo cmd_run[$#] "$@"
	if [ $# -ne 1 ] ; then 
		cat << __HELP__
usage: $0 run file

Runs file in the emulator configured. The behaviour depends on the filetype:
   .autococo => fetch the file in URL or source field, and execute
   .DSK, .CAS, .ZIP or .CCC => looks for an .autococo in the same directory
	infer, if it doesn't exit

__HELP__
		return -1;
	fi

	local file="$1"
	local filetype="${file##*.}"
	if [[ ${filetype,,} == "autococo" ]] ; then
		# user passsed autococo, but not the ZIP/DSK/CAS/CCC
		autococo="$file"

		autococo_load "$autococo"
		local dir ; dir=$(dirname "$file")
		file="$dir/$coco_package_file"
		if [[ ! -f "$file" ]] ; then file="${1%.*}.zip" ; fi
		if [[ ! -f "$file" ]] ; then file="${1%.*}.ZIP" ; fi
		if [[ ! -f "$file" ]] ; then file="${1%.*}.DSK" ; fi
		if [[ ! -f "$file" ]] ; then file="${1%.*}.dsk" ; fi
		if [[ ! -f "$file" ]] ; then file="${1%.*}.CCC" ; fi
		if [[ ! -f "$file" ]] ; then file="${1%.*}.ccc" ; fi
		if [[ ! -f "$file" ]] ; then file="${1%.*}.CAS" ; fi
		if [[ ! -f "$file" ]] ; then file="${1%.*}.cas" ; fi
		if [[ ! -f "$file" ]] ; then
			if [[ -z "$coco_package_url" ]] ; then
				error "Passed autococo has no URL to download, check if there is the original ZIP/DSK/CAS/CCC file with the same base name as the autococo file or correct the package:url parameter."			else
				return 1
			else
				cmd_download "$coco_package_url"
				# cmd_download already sets $file
				if [[ $? != 0 ]] ; then
					error "Cannot find/download necessary files to run this autococo."
				fi
			fi
		fi
			# change the filetype variable for the real one
		filetype="${file##*.}"
	else # all other extensions
		# user passsed ZIP/DSK/CAS/CCC, but not the autococo
		# looks for an autococo file and creates it if it is not found
		local autococo="${file%.*}.autococo"
		if [[ ! -f "$autococo" ]] ; then
			cmd_infer "$1" "$autococo"
		fi

		autococo_load "$autococo"
	fi

	# at this point $file has the ZIP/DSK/CAS/CCC and $autococo the autococo (loaded in coco_* vars)

	case ${filetype,,} in
	zip)
	  WORKDIR="$WORKDIR/run"
	  unzip_at "$1" "$WORKDIR"
	  ;;
	dsk)
	  coco_setup_floppy0="$1"
	  WORKDIR=$(dirname "$1")
	  ;;
	cas)
	  coco_setup_cassette="$1"
	  WORKDIR=$(dirname "$1")
	  ;;
	ccc)
	  coco_setup_rompack="$1"
	  WORKDIR=$(dirname "$1")
	  ;;
	*)
	  echo NOT IMPLEMENTED
	  exit -1
	  ;;
	esac

	call_emulator
}

case "$1" in
  run)
    shift
    cmd_run "$@"
    exit $?
    ;;
  infer)
    shift
    cmd_infer "$@"
    exit $?
    ;;
  download)
    shift
    cmd_download "$@"
    exit $?
    ;;
  *)
    cat << __HELP__
usage: $0 command parameters ...

where command is:
  infer _file_ = infer the AUTOCOCO from file
  run _autococo_file_ _file_ = execute the file in the emulator using autococo as configuration
  download [-f] _url_ = downloads URL and stores in the archive (-f forces the download if file already exist)
__HELP__
    exit -1
    ;;
esac
