#!/bin/sh
function help() {
	cat << __HELP__
usage: $(basename "$0") proxy_server[:proxy_port] [user password]

Sets proxy environment variables

__HELP__
}

case $# in 
	1)
		PROXY_SERVER="$1"
	;;
	3)
		PROXY_SERVER="$1"
		PROXY_SECRET="${2}:${3}@"
	;;
	*)
		help
	;;
esac

export http_proxy=http://${PROXY_SECRET}${PROXY_SERVER}
export https_proxy=$http_proxy
export no_proxy="::1,127.0.0.1,localhost,169.254.169.254,$HOSTNAME,*.$(domainname)"
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
export NO_PROXY=$no_proxy

echo "New proxy: ${http_proxy}"
